
package br.ifrn.tads.poo.biblioteca.view;

import br.ifrn.tads.poo.biblioteca.controller.UsuarioController;
import br.ifrn.tads.poo.biblioteca.usuario.Administrador;
import br.ifrn.tads.poo.biblioteca.usuario.Usuario;
import javax.swing.JOptionPane;

public class TelaLogin extends javax.swing.JFrame {
    private UsuarioController usuarioController;
    
    public TelaLogin() {
        usuarioController = new UsuarioController();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLogin = new javax.swing.JButton();
        jLabelIconeTelaLogin = new javax.swing.JLabel();
        jLabelUserLogin = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jTextFieldUserLogin = new javax.swing.JTextField();
        jLabelFundoTelaLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonLogin.setBackground(new java.awt.Color(204, 204, 255));
        jButtonLogin.setText("Entrar");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogin);
        jButtonLogin.setBounds(310, 300, 80, 28);

        jLabelIconeTelaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ifrn/tads/poo/biblioteca/imagens/iconeLogin.png"))); // NOI18N
        getContentPane().add(jLabelIconeTelaLogin);
        jLabelIconeTelaLogin.setBounds(150, -40, 260, 250);

        jLabelUserLogin.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabelUserLogin.setForeground(new java.awt.Color(255, 153, 51));
        jLabelUserLogin.setText("Login :");
        getContentPane().add(jLabelUserLogin);
        jLabelUserLogin.setBounds(110, 230, 100, 30);

        jLabelSenha.setFont(jLabelUserLogin.getFont());
        jLabelSenha.setForeground(new java.awt.Color(255, 153, 51));
        jLabelSenha.setText("Senha :");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(110, 260, 100, 30);

        jLabel1.setFont(jLabelUserLogin.getFont());
        jLabel1.setForeground(jLabelSenha.getForeground());
        jLabel1.setText("Criar Conta");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 330, 140, 20);
        getContentPane().add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(210, 260, 180, 30);

        jTextFieldUserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUserLogin);
        jTextFieldUserLogin.setBounds(210, 230, 180, 30);

        jLabelFundoTelaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ifrn/tads/poo/biblioteca/imagens/telaLogin.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoTelaLogin);
        jLabelFundoTelaLogin.setBounds(-8, 0, 560, 371);

        setSize(new java.awt.Dimension(565, 410));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUserLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserLoginActionPerformed
    // Testa se login e senha nos campo são válidos,se sim,abre tela principal se ñ, exibe um pop up com erro!
    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        //Verifica se o usuario existe no sistema. o usuario padrao é login:admin | passowrd:senha
        Usuario user = usuarioController.login(jTextFieldUserLogin.getText(),jPasswordFieldSenha.getText());
        if (user!=null){
            
            //Yuri depois de verificar se ele logou, aqui vc verifica que tipo de usuario ele é
            if(user instanceof Administrador){  //Administrador?
                TelaPrincipal telaPrincipal = new TelaPrincipal();
                telaPrincipal.setVisible(true);
                dispose();
            } else if(user instanceof Usuario) { //Padrão?
                TelaPrincipalPadrao telaPadrao = new TelaPrincipalPadrao();
                telaPadrao.setVisible(true);
                dispose();
            }
                        
        }else{
            JOptionPane.showMessageDialog(null, "Login ou Senha inválido.","Erro",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        CadastrarCliente cCliente = new CadastrarCliente();
        cCliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFundoTelaLogin;
    private javax.swing.JLabel jLabelIconeTelaLogin;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelUserLogin;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldUserLogin;
    // End of variables declaration//GEN-END:variables
}
